on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn prepublishOnly
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: "@unpic/placeholder"
      - name: Authenticate Yarn
        run:
          yarn config set npmAuthToken $NPM_AUTH_TOKEN && yarn config set
          registry https://registry.npmjs.org/
        if: ${{ steps.release.outputs.release_created }}
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: yarn npm publish
        if: ${{ steps.release.outputs.release_created }}
